#!/bin/sh

# This script is used by the compiling scripts (configure, Makefile)
# to determine which executables to use.

#
# Echo the name of this architecture
#
# Usage: ./architecture
#
# On ULTRIX use: sh5 ./architecture
#

# Find out what kind of system this is
UNAME="`uname -a`"

case "$UNAME" in
Darwin*)
        # Macintosh Power PC running OS X  
        SYS="Darwin"
        ;;
Linux*)
	# PC running Linux
	SYS="Linux"
	;;
*)	# Unknown system
	SYS="unknown"
esac

echo $SYS

